### ISSUE TITLE
Synergistic Network of Depressive Traits

### ISSUE THREAD

**Issue by ErnWg** [brainhacklucca/brainhacklucca.github.io#4]
### Title

Synergistic Network of Depressive Traits

### Leaders

Ern Wong (@ern_wng)
Emanuele Agrimi

### Collaborators

Alessandra Algieri
+2

### Brainhack Global 2023 Event

Brainhack Lucca

### Project Description

Higher-order interactions provide sophisticated descriptions of complex and dynamical networks
beyond what contemporary pairwise analysis can capture. Particularly, to support
cognitive functions, brain regions are thought to collaborate synergistically, i.e. by means of
complex and rich patterns that only arise from the combination of the activity of multiple regions.
Since these synergies are thought to subserve higher cognitive functions, they could contribute
to our understanding of psychiatric impairments. This project thus aims to build synergistic
networks of brain function from resting-state fMRI and to identify network characteristics that
may be indicative of depressive traits, and that may help in patient classification.

### Goals for Brainhack Global

- Create a pipeline for building and analysing synergistic networks.
- Leverage rs-fMRI data from HCP Young Adult to identify network characteristics that
correlate with depressive traits measured from a composite scale.
- Preprocess functional and anatomical data from an independent dataset (Bezmaternykh
et al., 2021).

### Good first issues

1. Create a composite scale of depressive traits from HCP behavioural and questionnaire
data
2. Correlation between composite scale and synergistic interactions from HCP
3. Preprocessing functional and anatomical data from an independent dataset
4. Build a synergistic network of the independent dataset
5. Build a classifier to test the independent dataset

### Communication channels

- Slack/Discord

### Skills

- Familiarity with fMRI
- General proficiency with Python/MATLAB/Bash
- Network analysis
- Data Visualisation and Communication

### What will participants learn?

- Preprocessing of anatomical and functional MRI data
- Higher-order interactions measures
- Network analysis
- Machine learning techniques

### Data to use

HCP Young Adult Dataset
https://openneuro.org/datasets/ds002748/versions/1.0.5

### Number of collaborators

1-3

### Image

![Screenshot 2023-11-28 154450](https://github.com/brainhacklucca/brainhacklucca.github.io/assets/71061018/6e6872b7-27df-4859-aac4-2f9826df4ccb)

### Type

coding_methods, method_development, pipeline_development, visualization

### Development status

1_basic structure

### Topic

connectome, data_visualisation, information_theory, machine_learning, statistical_modelling

### Tools

AFNI, ANTs, FSL, Jupyter, Nipype

### Programming language

Matlab, Python, shell_scripting

### Modalities

fMRI

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhacklucca my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by ErnWg** [comment]
Hi @brainhacklucca my project is ready!

**Comment by StanSStanman** [comment]
Hi @ErnWg, your project has been successfully added to the BHL 2023 website! 🎉
See you soon!
Ruggero
