### ISSUE TITLE
PACman

### ISSUE THREAD

**Issue by Gytle** [brainhacklucca/brainhacklucca.github.io#5]
### Title

**PACman**: finding **P**hase-**A**mplitude **C**oupling events in continuous EEG recordings in an automatic **man**ner

### Leaders

Davide Marzoli
Guillaume Legendre

### Brainhack Global 2023 Event

Brainhack Lucca

### Project Description

Neuronal oscillation, a process where neurons communicate with rhythmic patterns, can be observed as waves in electroencephalographic (EEG) recordings of brain signals. This communication mode is a cost-efficient way to achieve various cognitive processes ranging from temporal binding of sensory inputs, attention selection to even memory consolidation. Recent developments in our understanding of neuronal oscillation suggest that the phase of slower oscillations can modulates the amplitude of faster neuronal oscillations, a phenomenon known as Phase-Amplitude Coupling (PAC). PAC can be observed in large part of the scalp with EEG and is a putative mechanism for distributing information among large-scale networks with implications for learning, memory consolidation and retrieval.

This project aims to develop an algorithm for detecting PAC events in continuous EEG recordings, focusing initially on the detection of slow-waves coupled with spindles since their co-occurrence is a well characterized phenomenon in sleep EEG and will serve as ‘ground-truth’ for the validation of the method.
 The successful method will be adapted to be extend to the cross-coupling of any kind of frequency range, increasing the possibility of usage to a broader extent and answering new biological questions.

Understanding the relationship between phase and amplitude, such as in the case of slow waves and spindles, can be useful for evaluating sleep quality and may help identify abnormalities in sleep patterns. The coupling between spindles and slow waves is tightly linked to memory consolidation and analyzing their interaction contributes to understanding memory processing and retention. Investigating abnormalities in phase-amplitude coupling can also provide insights into disorders such as Alzheimer’s disease, epilepsy and schizophrenia, and be used as potential biomarkers. Moreover understanding neural synchronization patterns can contribute to the development of BCIs and neurofeedback systems

Despite its relatively easy implementation, this project offers the possibility to answer relevant biological questions. The cross-coupling of brainwaves represents an interesting and yet poorly investigated strategy by which the brain operates and may reveal important physiological mechanisms. For instance, it has been shown that the coupling of slow-waves and spindle is tightly related to hippocampal ripples (which otherwise would not be observable through non-invasive techniques).

### Link to project repository/sources

https://github.com/Gytle/PACman.git

### Goals for Brainhack Global

1. Review the literature on methods of Phase-Amplitude Coupling (PAC) to determine the methods best suited for our algorithm.
2. Detect visually specific PAC events (namely Slow-oscillation-spindle coupling) in whole-night EEG recordings.
3. Implement the method to extract PAC in a time-frequency manner.
4. Implement a clustering algorithm to detect and label automatically changes in PAC.
5. Test and validate the full algorithm on the previously labeled whole-night EEG recordings.

### Good first issues

1. issue one:
2. issue two:

### Communication channels

https://join.slack.com/t/pacman-jxz3889/shared_invite/zt-27sl3wnna-fZfwNWo5GYrSSTBPQP4IDA

### Skills

- Python coding
- Experience in EEG
- Experience in signal processing
- Experience in clustering algorithm

### What will participants learn?

Participants will be introduced to EEG data processing, coding with python and machine learning/clustering algorithms. The purpose of the project is to associate participants with diverse backgrounds and learn from the skills of others.

### Data to use

The project will be based on a freely available dataset of overnight polysomnography including electroencephalography, electroocculography and electromyography:
Rezaei, Mohammad; Mohammadi, Hiwa ; Khazaie, Habibolah  (2017), “EEG/EOG/EMG data from a cross sectional study on psychophysiological insomnia and normal sleep subjects”, Mendeley Data, V1, doi: 10.17632/3hx58k232n.1

### Number of collaborators

3-5

### Credit to collaborators

Members will be credited on public platforms hosting the algorithm code.

### Image

![PACMAN_logo](https://github.com/brainhacklucca/brainhacklucca.github.io/assets/53912562/6cca5bf0-200a-4c01-ac6b-d6d6d7ffaa7d)

### Type

method_development

### Development status

0_concept_no_content

### Topic

physiology, reproducible_scientific_methods

### Tools

MNE

### Programming language

Python

### Modalities

EEG

### Git skills

1_commit_push

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhacklucca my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by Gytle** [comment]
Hi @brainhacklucca my project is ready!

**Comment by Gytle** [comment]
Twitter-sized summary:
Phase-Amplitude Coupling (PAC) is the process by which the phase of slow brain waves influences the amplitude of faster brain rhythms. This mode of communication between neuronal populations appears to be instrumental in many cognitive functions, particularly in memory formation, consolidation, and retrieval. In the PACman project, we are embarking on a journey to identify meaningful changes in PAC within continuous EEG recordings.

**Comment by StanSStanman** [comment]
Hi @Gytle, your project has been successfully added to the BHL 2023 website! 🎉
See you soon!
Ruggero
