### ISSUE TITLE
EEG-Based Sensory Classification using Machine Learning

### ISSUE THREAD

**Issue by LindaFiorini** [brainhacklucca/brainhacklucca.github.io#6]
### Title

EEG-Based Sensory Classification using Machine Learning

### Leaders

Linda Fiorini e Francesco Pietrogiacomi

### Brainhack Global 2023 Event

Brainhack Lucca

### Project Description

Understanding how the brain perceives the world has always been one of the most intriguing topics in neuroscience. We want to apply machine learning (ML) techniques to classify the electrophysiological signal of the brain recorded during sensory stimulation in healthy subjects. This project endeavors to decode the unique neural signatures associated with auditory and visual stimulation by integrating ML and neuroscience, in particular electroencephalography (EEG) data. ML has been applied to EEG in various fields, such as motor imagery (e.g. Amin et al., 2019) and emotions recognition (Wang et al., 2021), as well as for clinical purposes (e.g. Ozdemir et Al., 2021) but only few researches on sensory processing using ML have been published. We will analyze EEG data collected for a study on anticipatory multisensory integration (Fiorini et al., 2023). 
Potential applications of this project could be extended to better understand brain activity in states of altered consciousness - i.e., sleep, vegetative state, and coma - as well as in the field of brain-computer interfaces (BCI). 
We aim to demonstrate the novel use of AI in enhancing our knowledge of neural dynamics, specifically in sensory processing. The interdisciplinary nature of this project - bridging neuroscience, artificial intelligence, and sensory psychology - offers a unique perspective and contributes significantly to the field of cognitive science and neurotechnology.

### Goals for Brainhack Global

- Deepen the literature about application of deep learning on EEG
- Define EEG data preprocessing pipeline
- Implement different models to classify EEG signal
- Train and test the models

### Communication channels

Slack/Discord/WhatsApp/Mail

### Skills

- EEG signal processing
- Machine Learning/Deep Learning
- Python programming

### What will participants learn?

Participants can learn or improve EEG signal processing knowledge and the implementation of Machine Learning models in Python 

### Data to use

Participants will be provided with preprocessed EEG data collected during passive tasks (volunteers saw or heard stimuli without performing any specific task).

### Number of collaborators

None

### Credit to collaborators

Future collaboration in later stages in case a collaborator is interested in continuing to work on the project.

### Image

![20231202_174637](https://github.com/brainhacklucca/brainhacklucca.github.io/assets/141327603/83e28270-ee1e-412b-b831-cba03fe0586d)

### Type

data_management, method_development

### Development status

0_concept_no_content

### Topic

deep_learning, machine_learning, neural_decoding, physiology

### Tools

MNE, other

### Programming language

Python

### Modalities

EEG

### Git skills

0_no_git_skills, 1_commit_push

### Things to do after the project is submitted and ready to review.

- [ ] Add a comment below the main post of your issue saying: `Hi @brainhacklucca my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by StanSStanman** [comment]
Hi @LindaFiorini, your project has been successfully added to the BHL 2023 website! 🎉
See you soon!
Ruggero
