### ISSUE TITLE
LRG: Zooming out the brain scales

### ISSUE THREAD

**Issue by tommasogili** [brainhacklucca/brainhacklucca.github.io#7]
### Title

LRG: Zooming out the brain scales

### Leaders

Tommaso Gili (X: @tommasogili)

### Brainhack Global 2023 Event

Brainhack Lucca

### Project Description

Structural connectivity in the brain is typically studied by reducing its observation to a single spatial resolution. However, the brain possesses a rich architecture organised over multiple scales linked to one another (Betzel and Bassett, 2017). Simple organising principles underlie the multiscale architecture of human structural brain networks, where the same connectivity law dictates short- and long-range connections between different brain regions over many resolutions. Such a multiscale property can be appreciated by progressively coarse-graining the connected anatomical regions by changing the observation resolution.
This project aims to apply a recently proposed graph coarse-graining method (the Laplacian Renormalization Group: Villegas et al., 2023) to the human connectome and identify the network density's role in identifying multiple connectivity scales. 

### Goals for Brainhack Global

•	To create a pipeline for an effective structural network sparsification, starting from probabilistic and deterministic tractography of multiple subjects.
•	To adapt the Laplacian Renormalization Group algorithm for the human connectome.
•	To establish the working limits of a non-geometric coarse-graining in terms of network density.

### Good first issues

1.	To define a strategy to create a consensus structural network from tractography.
2.	To realise a filtration process that reduces the network's density, preserving the topology. 
3.	To extract a multiresolution description of the human connectome using the Laplacian Renormalization Group approach.

### Communication channels

•	Slack/Whatsapp/Email

### Skills

•	Familiarity with DTI and Tractography
•	General proficiency with Python/MATLAB/Bash
•	Network analysis
•	Data Visualisation and Communication

### What will participants learn?

•	To calculate a representative structural network across subjects.
•	To reduce a network density, preserving its topology.
•	To renormalise a network without any geometric constrain.

### Data to use

Participants will receive probabilistic and deterministic tractography from healthy human DTI measurements.

### Number of collaborators

3-5

### Image

Leave this text if you don't have an image yet.
![Pict_Brain_LRG_BrainHack](https://github.com/brainhacklucca/brainhacklucca.github.io/assets/47632024/f7130e52-90eb-402d-a611-09a5fbbfefc8)

### Type

coding_methods, method_development, pipeline_development

### Development status

1_basic structure

### Topic

connectome, neural_networks, tractography

### Tools

Jupyter, other

### Programming language

Matlab, Python

### Modalities

DWI

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhacklucca my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by StanSStanman** [comment]
Hi @tommasogili, your project has been successfully added to the BHL 2023 website! 🎉
See you soon!
Ruggero
